standardtest('count.csv','pois',nseg=2,spike=T)
standardtest('count.csv','pois',nseg=1,spike=T)
standardtest('count.csv','nbd',nseg=1,spike=T)
standardtest('contime.csv','exp',pop=1499)
standardtest('contime.csv','eg',pop=1499)
standardtest('contime.csv','wg',pop=1499)
standardtest('contime.csv','gg',pop=1499)
standardtest('distime.csv','geom',pop=1000)
standardtest('distime.csv','bg',pop=1000)
standardtest('distime.csv','dw',pop=1000)
standardtest('distime.csv','bdw',pop=1000)
standardtest('choice.csv','bb')

standardtest('pnbd.csv','pexp')
standardtest('pnbd.csv','bgnbd')
standardtest('bgbb.csv','bgbb')
standardtest('pnbd.csv','pnbd')

d1=read.csv(r('pnbd.csv'))
d2=read.csv(r('bgbb.csv'))

a=fm(d1,'pexp',1)
b=fm(d1,'pexp',2)
c=fm(d1,'bgnbd',1)
d=fm(d1,'bgnbd',2)
e=fm(d1,'pnbd',1)
f=fm(d1,'pnbd',2)
g=fm(d2,'bgbb',1)
h=fm(d2,'bgbb',2,tries=10)

par(mfrow=c(2,4))
plot(cumtracking(a))
plot(cumtracking(b))
plot(cumtracking(c))
plot(cumtracking(d))
plot(cumtracking(e))
plot(cumtracking(f))
plot(cumtracking(g))
plot(cumtracking(h))
plot(growth(cumtracking(a)))
plot(growth(cumtracking(b)))
plot(growth(cumtracking(c)))
plot(growth(cumtracking(d)))
plot(growth(cumtracking(e)))
plot(growth(cumtracking(f)))
plot(growth(cumtracking(g)))
plot(growth(cumtracking(h)))


x=c(rnorm(800,15,2),rnorm(200,-10,4))
model=fm(x,'norm',nseg=2,tries=50,b=2);model