setwd('C:\\Users\\Andrew\\Desktop\\Workspace\\models\\fader')
source('utilities.R')
source('counting.R')
source('contime.R')
source('distime.R')
source('choice.R')
r=function(str) return(paste('raw',str,sep='\\'))

standardtest('count.csv','pois')
standardtest('count.csv','nbd')
standardtest('contime.csv','eg',num=1499)
standardtest('contime.csv','wg',num=1499)
standardtest('contime.csv','gg',num=1499)
standardtest('distime.csv','geom')
standardtest('distime.csv','bg')
standardtest('distime.csv','dw')
standardtest('distime.csv','bdw')
standardtest('choice.csv','bb')

data.dir=read.csv(r('dirich.csv'))
mod=c(0.195,0.054,0.060,0.116,0.362,0.139,0.151,0.175)
dirPen(mod,data.dir)
dirFreq(mod,data.dir)
dirOnce(mod,data.dir)
dirLoyal(mod,data.dir)
dirMkt(mod,data.dir)
dirScr(mod,data.dir)