#install.packages('gsl')
rm(list=ls())
setwd('C:\\Users\\Andrew\\Desktop\\Workspace\\models\\fader')
source('fmspec.R')
source('utilities.R')
source('counting.R')
source('contime.R')
source('distime.R')
source('integrated.R')
source('other.R')
source('choice.R')
source('dirmethods.R')
r=function(str) return(paste('raw',str,sep='\\'))

# TODO tracking plot for pnbd is still different